apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  JWT_KEY: dGhpc2lzbXkgc2VjcmV0
  SALT_FACTORY: MTA=
  STRIPE_KEY: c2tfdGVzdF81MUd5c3ZBR3pPMDIwMkpVYUtTT0V4WHZ2Z2dhemNoSk9oZDdDS3lPNFVYYUFuM1p6VDdGU1p6cTh6ckxLaFk0aFBiZ2dCcnppY1FsSExhWjdQMEtWaEFQRTAwb21SSExhQUs=
